# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 12:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0002_auto_20160330_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='homeScore',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='match',
            name='visitorScore',
            field=models.IntegerField(),
        ),
    ]
