# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 12:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0004_auto_20160330_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='match',
            name='homeScore',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='match',
            name='visitorScore',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
