# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-30 11:24
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amountBets', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('homeTeam', models.CharField(max_length=30)),
                ('visitorTeam', models.CharField(max_length=30)),
                ('homeScore', models.IntegerField()),
                ('visitorScore', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('login', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=15)),
                ('adm', models.BooleanField(default=False)),
                ('credits', models.FloatField(default=10.0, validators=[django.core.validators.MinValueValidator(0.0)])),
            ],
        ),
        migrations.AddField(
            model_name='bet',
            name='game',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bolao.Match'),
        ),
        migrations.AddField(
            model_name='bet',
            name='userBets',
            field=models.ManyToManyField(to='bolao.User'),
        ),
    ]
