# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 18:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0007_user_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchRegistration',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('homeTeam', models.CharField(max_length=30)),
                ('visitorTeam', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=10)),
                ('hora', models.CharField(max_length=6)),
            ],
        ),
        migrations.RemoveField(
            model_name='bet',
            name='game',
        ),
        migrations.RemoveField(
            model_name='bet',
            name='userBets',
        ),
        migrations.DeleteModel(
            name='Bet',
        ),
        migrations.DeleteModel(
            name='Match',
        ),
    ]
