# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 18:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0009_bet_matchresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='homeScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='matchresult',
            name='visitorScore',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='matchresult',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
