# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0010_auto_20160401_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='_game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bolao.MatchRegistration'),
        ),
        migrations.AddField(
            model_name='bet',
            name='amountofBets',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='bet',
            name='userBets',
            field=models.ManyToManyField(to='bolao.User'),
        ),
    ]
