# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-01 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0011_auto_20160401_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchresult',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bolao.MatchRegistration'),
        ),
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.AutoField(default=None, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='login',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
