# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-02 22:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0014_auto_20160402_1911'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bet',
            name='userBets',
        ),
        migrations.AddField(
            model_name='bet',
            name='userBets',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bolao.User'),
        ),
    ]
