# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-04 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0018_ranking'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegisterBet',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('homeTeam', models.CharField(max_length=30)),
                ('visitorTeam', models.CharField(max_length=30)),
                ('date', models.CharField(max_length=10)),
                ('hora', models.CharField(max_length=6)),
            ],
        ),
    ]
