# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-04 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0019_registerbet'),
    ]

    operations = [
        migrations.AddField(
            model_name='bet',
            name='homeScore',
            field=models.CharField(default=0, max_length=1),
        ),
        migrations.AddField(
            model_name='bet',
            name='visitorScore',
            field=models.CharField(default=0, max_length=1),
        ),
    ]
