# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 11:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0020_auto_20160404_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerbet',
            name='game',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='bolao.MatchRegistration'),
        ),
        migrations.AlterField(
            model_name='bet',
            name='homeScore',
            field=models.CharField(default=0, max_length=2),
        ),
        migrations.AlterField(
            model_name='bet',
            name='visitorScore',
            field=models.CharField(default=0, max_length=2),
        ),
    ]
