# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-05 22:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0023_auto_20160405_0827'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchregistration',
            name='amountOfCredits',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
    ]
