# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0024_matchregistration_amountofcredits'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchregistration',
            name='message',
            field=models.CharField(default='', max_length=300),
        ),
    ]
