# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0025_matchregistration_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchregistration',
            name='message',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
