# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 23:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0026_auto_20160412_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerbet',
            name='message',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
