# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-12 23:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0027_registerbet_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registerbet',
            name='message',
        ),
    ]
