# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 00:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0029_auto_20160412_2035'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchregistration',
            name='message',
        ),
        migrations.AddField(
            model_name='bet',
            name='message',
            field=models.CharField(blank=True, default='Aposta Disponível', max_length=300),
        ),
    ]
