# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-13 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bolao', '0031_auto_20160412_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bet',
            name='message',
            field=models.CharField(blank=True, default='Disponível', max_length=300),
        ),
    ]
